name: Test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Node Script with Supabase Key
        env:
          SUPABASEKEY: ${{ secrets.supabasekey }}
        run: node myscript.js
